// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
//using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace Selenium.Tests.Integration
{
    [TestClass]
    public class LoginTest
    {
        private IWebDriver driver;
        public IDictionary<string, object> vars { get; private set; }
        private IJavaScriptExecutor js;

        [TestInitialize()]
        public void SetUp()
        {
            driver = new ChromeDriver();
            js = (IJavaScriptExecutor)driver;
            vars = new Dictionary<string, object>();
        }

        [TestCleanup()]
        public void TearDown()
        {
            driver.Quit();
        }

        [TestMethod()]
        public void Login()
        {
            try
            {
                driver.Navigate().GoToUrl("https://localhost:44399/login");
                driver.Manage().Timeouts().ImplicitWait = TimeSpan.FromSeconds(10000);
                driver.Manage().Window.Size = new System.Drawing.Size(945, 744);
                driver.FindElement(By.Name("Name")).Click();
                driver.FindElement(By.Name("Name")).SendKeys("abc");
                driver.FindElement(By.Name("Password")).Click();
                driver.FindElement(By.Name("Password")).SendKeys("abc");
                driver.FindElement(By.CssSelector("tr:nth-child(3) input")).Click();
                Assert.AreEqual(driver.FindElement(By.CssSelector("tr:nth-child(4) > td")).Text, "login success");
            }
            catch (Exception ex)
            {
                driver.Dispose();
            }
        }
    }
}